package com.cpcn.dao;

import java.util.List;

import com.cpcn.domain.Student;

public interface StudentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table STUDENT_TEST
	 *
	 * @mbggenerated Tue May 23 14:37:06 CST 2017
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table STUDENT_TEST
	 *
	 * @mbggenerated Tue May 23 14:37:06 CST 2017
	 */
	int insert(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table STUDENT_TEST
	 *
	 * @mbggenerated Tue May 23 14:37:06 CST 2017
	 */
	int insertSelective(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table STUDENT_TEST
	 *
	 * @mbggenerated Tue May 23 14:37:06 CST 2017
	 */
	Student selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table STUDENT_TEST
	 *
	 * @mbggenerated Tue May 23 14:37:06 CST 2017
	 */
	int updateByPrimaryKeySelective(Student record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table STUDENT_TEST
	 *
	 * @mbggenerated Tue May 23 14:37:06 CST 2017
	 */
	int updateByPrimaryKey(Student record);

	List<Student> selectAll();

	long count();
}