package com.cpcn.domain;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_TEST.ID
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_TEST.STU_NAME
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_TEST.GENDER
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    private Long gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_TEST.AGE
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    private Long age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STUDENT_TEST.ADDRESS
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_TEST.ID
     *
     * @return the value of STUDENT_TEST.ID
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_TEST.ID
     *
     * @param id the value for STUDENT_TEST.ID
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_TEST.STU_NAME
     *
     * @return the value of STUDENT_TEST.STU_NAME
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_TEST.STU_NAME
     *
     * @param stuName the value for STUDENT_TEST.STU_NAME
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public void setStuName(String stuName) {
        this.stuName = stuName == null ? null : stuName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_TEST.GENDER
     *
     * @return the value of STUDENT_TEST.GENDER
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public Long getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_TEST.GENDER
     *
     * @param gender the value for STUDENT_TEST.GENDER
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public void setGender(Long gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_TEST.AGE
     *
     * @return the value of STUDENT_TEST.AGE
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public Long getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_TEST.AGE
     *
     * @param age the value for STUDENT_TEST.AGE
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public void setAge(Long age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STUDENT_TEST.ADDRESS
     *
     * @return the value of STUDENT_TEST.ADDRESS
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STUDENT_TEST.ADDRESS
     *
     * @param address the value for STUDENT_TEST.ADDRESS
     *
     * @mbggenerated Tue May 23 14:37:06 CST 2017
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

	@Override
	public String toString() {
		return "Student [id=" + id + ", stuName=" + stuName + ", gender=" + gender + ", age=" + age + ", address=" + address + "]";
	}
    
}